// Generates per-scene narration WAVs with Gemini TTS (voice Kore) via lib/media/tts.
// Run under the server-only shim:
//   npx tsx --require ./scripts/_no-server-only.cjs scripts/video/narrate.ts
// Output: /tmp/preproom-video/audio/<scene>.wav  (+ manifest.json with durations)
import { config } from "dotenv";
config({ path: ".env.local" });

import { generateSpeech } from "@/lib/media/tts";
import { writeFileSync, mkdirSync, existsSync, readFileSync } from "node:fs";
import { execFileSync } from "node:child_process";

const OUT = "/tmp/preproom-video/audio";
mkdirSync(OUT, { recursive: true });

// Narration lines, trimmed to fit each scene. Light pacing cues steer Gemini.
// Keep them tight — total target ~2:50.
const LINES: Record<string, string> = {
  "card-open":
    "Say warmly and clearly: PrepRoom — a persistent teaching agent for every language learner.",
  landing:
    "Independent language tutors spend about forty-five minutes preparing for every single student. Multiply that across fifteen students, and you lose an entire workday every week — just on prep. PrepRoom gives them their copilot, starting at nineteen dollars a month.",
  "studio-anna":
    "This is Anna, one of my students. The agent already knows she's B-one, that she mixes up past tenses, and where her work-call English breaks down. I didn't paste any of that today — every fact is tagged with its source: a chat, or her last lesson video.",
  "chat-focus":
    "So I just ask: what should we focus on next? Watch the agent trace — it searches Anna's memory and her video analysis, then answers from evidence. Her past-tense errors, her goals. No generic advice.",
  "chat-homework":
    "Now I ask it to build homework targeting exactly those past-tense errors — with a listening clip and an image flashcard. It assembles a full practice set, calibrated to B-one, and saves it as an artifact. A second agent checks the whole set against a pedagogy rubric before it ever reaches me.",
  share:
    "Anna opens a public link — no account, no friction — and gets instant feedback on every answer. That audio was generated by Gemini text-to-speech. The flashcard image, generated too. Not pre-recorded files.",
  "chat-results":
    "And the exercises Anna just finished? Her results flowed straight back into memory. So I can ask: how did Anna do? It knows the score — because homework results are memory facts. That's a closed learning loop.",
  "autonomous-artifacts":
    "But here's the real moment. I uploaded a lesson recording earlier. While I was away — no chat, no prompts — the agent watched the video, found her struggles, and drafted the next lesson plan and homework on its own. They're already waiting in her artifact list.",
  evals:
    "And you can trust it. Every exercise is validated against a schema before it ships. On a ten-case golden eval, one hundred percent schema validity, and four-point-four-seven out of five on a pedagogy rubric judged by Gemini.",
  arch:
    "The whole thing is one Cloud Run service. An ADK agent with an MCP exercise catalog, Gemini multimodal for chat, homework, and video, Cloud SQL, Cloud Storage, and Pub/Sub. One service, fully deployed.",
  "card-closing":
    "PrepRoom watches lessons, remembers the evidence, and turns it into the next teaching action — automatically. Forty-five minutes of prep, down to zero.",
};

function wavDuration(path: string): number {
  const out = execFileSync("/opt/homebrew/bin/ffprobe", [
    "-v", "error", "-show_entries", "format=duration", "-of", "csv=p=0", path,
  ]).toString().trim();
  return parseFloat(out);
}

async function main() {
  const only = process.argv.slice(2);
  const scenes = Object.keys(LINES).filter((s) => only.length === 0 || only.includes(s));
  // Merge into any existing manifest so single-scene runs don't clobber it.
  const manifest: Record<string, { duration: number; text: string }> =
    existsSync(`${OUT}/manifest.json`) ? JSON.parse(readFileSync(`${OUT}/manifest.json`, "utf8")) : {};
  for (const scene of scenes) {
    const text = LINES[scene];
    process.stdout.write(`TTS ${scene} ... `);
    const wav = await generateSpeech(text, { voice: "Kore" });
    const path = `${OUT}/${scene}.wav`;
    writeFileSync(path, wav);
    const dur = wavDuration(path);
    manifest[scene] = { duration: dur, text };
    console.log(`${dur.toFixed(1)}s`);
  }
  writeFileSync(`${OUT}/manifest.json`, JSON.stringify(manifest, null, 2));
  const total = Object.values(manifest).reduce((a, b) => a + b.duration, 0);
  console.log(`\nTotal narration: ${total.toFixed(1)}s across ${scenes.length} scenes`);
}
main().catch((e) => { console.error(e); process.exit(1); });
